# Generated by Django 5.0.4 on 2024-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
