# Generated by Django 5.0.4 on 2024-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
