# Generated by Django 5.0.4 on 2024-05-23 16:49

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=154)),
                ('price', models.FloatField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('info', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Product',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=product.models.save_product_photo)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.product')),
            ],
            options={
                'verbose_name': 'Фото продукции',
                'verbose_name_plural': 'Фотографии продукции',
                'db_table': 'ProductPhoto',
            },
        ),
    ]
