# Generated by Django 5.0.4 on 2024-05-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=154)),
                ('price', models.IntegerField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('count', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product_photoes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoes', to='product.product')),
            ],
            options={
                'verbose_name': 'Фото продукции',
                'verbose_name_plural': 'Фотографии продукции',
                'db_table': 'ProductPhoto',
            },
        ),
    ]
