# Generated by Django 5.0.4 on 2024-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='product_<django.db.models.fields.related.ForeignKey>_photoes'),
        ),
    ]
