# Generated by Django 5.0.4 on 2024-05-03 15:27

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to=product.models.save_product_photo),
        ),
    ]
