# Generated by Django 5.0.4 on 2024-05-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_weight_product_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
