# Generated by Django 5.0.4 on 2024-05-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_alter_productphoto_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.BigIntegerField(unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Р', 'Рассмотрение'), ('С', 'Склад'), ('Д', 'Доставка'), ('П', 'Получено')], default='Рассмотрение', max_length=46)),
                ('comment', models.TextField()),
                ('products', models.ManyToManyField(db_table='OrderProduct', related_name='orders', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('orders', models.ManyToManyField(db_table='OrderCategory', related_name='categories', to='order.order')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
            },
        ),
    ]
