# Generated by Django 5.0.4 on 2024-05-23 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Н', 'Новый'), ('О', 'В обработке'), ('В', 'Выполнен'), ('ОТ', 'Отменен')], default='Н', max_length=46)),
                ('comment', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0, editable=False)),
                ('place', models.TextField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('orders', models.ManyToManyField(db_table='OrderCategory', related_name='categories', to='order.order')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='product.product')),
            ],
            options={
                'verbose_name': 'Продукт заказа',
                'verbose_name_plural': 'Продукты заказов',
                'db_table': 'OrderProduct',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(editable=False, related_name='orders', through='order.OrderProduct', to='product.product'),
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Н', 'Новый'), ('О', 'В обработке'), ('Р', 'Решен'), ('ОТ', 'Отклонен')], default='Н', max_length=46)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='order.order')),
            ],
            options={
                'verbose_name': 'Запрос на заказ',
                'verbose_name_plural': 'Запросы на заказы',
                'db_table': 'OrderRequest',
                'ordering': ['-order__creation_time'],
            },
        ),
    ]
