# Generated by Django 5.0.4 on 2024-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='identification_number',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
