# Generated by Django 5.0.4 on 2024-05-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderproduct_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='count',
        ),
    ]
