# Generated by Django 5.0.4 on 2024-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
