# Generated by Django 5.0.4 on 2024-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Н', 'Новый'), ('О', 'В обработке'), ('В', 'Выполнен'), ('ОТ', 'Отменен')], default='Н', max_length=46),
        ),
    ]
