# Generated by Django 5.0.4 on 2024-05-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Запрос на заказ',
                'verbose_name_plural': 'Запросы на заказы',
                'db_table': 'OrderRequest',
            },
        ),
    ]
