# Generated by Django 5.0.4 on 2024-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_orderrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('Н', 'Новый'), ('О', 'В обработке'), ('Р', 'Решен'), ('ОТ', 'Отменен')], default='Н', max_length=46),
        ),
    ]
