# Generated by Django 5.0.4 on 2024-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_options_alter_orderrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
