# Generated by Django 5.0.4 on 2024-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_orderproduct_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_price',
        ),
    ]
