# Generated by Django 5.0.4 on 2024-05-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_orderproduct_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
